### ISSUE TITLE
notes for gpu set up on kubernetes

### ISSUE THREAD

**Issue by eeholmes** [SAFS-Varanasi-Internship/Summer-2024#4]
https://learn.microsoft.com/en-us/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool

**Comment by eeholmes** [comment]
* Got GPU credits on Azure for Standard_NC4as_T4_v3
* Added Standard_NC4as_T4_v3 node pool. min 1 max 2
* Added this to the config file
```
      - display_name: NVIDIA Tesla T4, 28 GB, 4 CPUs
        description: "Start a container on a dedicated node with a GPU"
        slug: "gpu"
        profile_options:
          image:
            display_name: Image
            choices:
              pytorch:
                display_name: Pangeo PyTorch ML Notebook
                default: true
                slug: "pytorch"
                kubespawner_override:
                  image: "quay.io/pangeo/pytorch-notebook:2023.09.19"
        kubespawner_override:
          environment:
            NVIDIA_DRIVER_CAPABILITIES: compute,utility
          mem_limit: null
          mem_guarantee: 14G
          node_selector:
            node.kubernetes.io/instance-type: Standard_NC4as_T4_v3
```
* I think the pangeo pytorch image has the drivers
